//! EIP-712 cross-validation against Python SDK (eth_account).
//! Vectors generated by tests/fixtures/generate_eip712_vectors.py.
//! Each test signs a typed data message with the same key and verifies
//! the signature matches byte-for-byte.

const std = @import("std");
const hlz = @import("hlz");
const eip712 = hlz.crypto.eip712;
const signer_mod = hlz.crypto.signer;
const Signer = signer_mod.Signer;
const Signature = signer_mod.Signature;

const test_key = "e908f86dbb4d55ac876378565aafeabc187f6690f046459397b17d9b9a19688e";
const is_mainnet = true;
const dest = hexToBytes(20, "0000000000000000000000000000000000000001");
const time: u64 = 1700000000000;

fn hexToBytes(comptime len: usize, hex: *const [len * 2]u8) [len]u8 {
    var out: [len]u8 = undefined;
    for (0..len) |i| {
        out[i] = std.fmt.parseInt(u8, hex[i * 2 ..][0..2], 16) catch unreachable;
    }
    return out;
}

fn expectSig(sig: Signature, expected_hex: *const [130]u8) !void {
    const expected = hexToBytes(65, expected_hex);
    try std.testing.expectEqualSlices(u8, &expected, &sig.toEthBytes());
}

test "UsdSend: matches Python SDK" {
    const s = try Signer.fromHex(test_key);
    const sig = try eip712.signUsdSend(s, is_mainnet, dest, "100.0", time);
    try expectSig(sig, "781c38d97da01f6a223d9a9198776649b43489c7d3ce3c5624d06e0f587b3d7237ab5d1e4213d1eb98bcab158570da660f9436ad2ed4ef1bb02009fa77189e5d1b");
}

test "Withdraw: matches Python SDK" {
    const s = try Signer.fromHex(test_key);
    const sig = try eip712.signWithdraw(s, is_mainnet, dest, "50.0", time);
    try expectSig(sig, "f6c89c11f24074179a5f82d9c93db1b4d50fc63ad4f2a32d088883d7c6e9dc2b1e97538fc6c6abe4bdfbbb78f6318c82d9747c5ae8eecde884a59012301bb26c1c");
}

test "UsdClassTransfer: matches Python SDK" {
    const s = try Signer.fromHex(test_key);
    const sig = try eip712.signUsdClassTransfer(s, is_mainnet, "1000.0", true, time);
    try expectSig(sig, "3b404cb12be6e4a7c5c1e14edc093496dc5783525fb65d698b4ae596a6bbd2743f9ccd30c7869d0ab45ce73759ac19fe95633b8741b3c869d84ed5c320ad6c251c");
}

test "TokenDelegate: matches Python SDK" {
    const s = try Signer.fromHex(test_key);
    const addr2 = hexToBytes(20, "0000000000000000000000000000000000000002");
    const sig = try eip712.signTokenDelegate(s, is_mainnet, addr2, 1000000000000000000, false, time);
    try expectSig(sig, "54e19bc5c40de2fc0acddec5e4d4c6af6adcdab080eb814421588c0db67d5427662617758972aadd6ff2c99a2f26cfd058da5aff018ba89d5187e3b1977685e01b");
}

test "ApproveBuilderFee: matches Python SDK" {
    const s = try Signer.fromHex(test_key);
    const addr3 = hexToBytes(20, "0000000000000000000000000000000000000003");
    const sig = try eip712.signApproveBuilderFee(s, is_mainnet, "0.001", addr3, time);
    try expectSig(sig, "a51af5fdb4c96ae617af813b2dd25622f7992223783624d3d53a23dbb7241a6d7e46324a3805e3de0b9195df8a676cce047ae9ebcadd179b8600acd6c8c6002f1c");
}

test "ApproveAgent: matches Python SDK" {
    const s = try Signer.fromHex(test_key);
    const addr4 = hexToBytes(20, "0000000000000000000000000000000000000004");
    const sig = try eip712.signApproveAgent(s, is_mainnet, addr4, "test-agent", time);
    try expectSig(sig, "6d8ec16448ec5b1bcf4a3c4a55422b17b517bd8e1b45de77341ac08ab5ab03506c95e43d8181e2d6d8b18c1374b41fee2c008c917ab2c73bf3c0540555c5d28b1b");
}

test "SpotSend: matches Python SDK" {
    const s = try Signer.fromHex(test_key);
    const sig = try eip712.signSpotSend(s, is_mainnet, dest, "PURR", "100.0", time);
    try expectSig(sig, "40ee8b3aa1e1d9ce2bbc568cd998dcffef77b1463a18c274b1eac65d0dfa868818124f33c6362d72b50e4df95bfd14fa87ab5e38ffbaca73987d8d26959860151b");
}

test "UserDexAbstraction: matches Python SDK" {
    const s = try Signer.fromHex(test_key);
    const addr5 = hexToBytes(20, "0000000000000000000000000000000000000005");
    const sig = try eip712.signUserDexAbstraction(s, is_mainnet, addr5, true, time);
    try expectSig(sig, "0437a119020cfac8ab095ee82b75dfa9f8ea4af218781c421f3ba7c710dee0db00d757ec7dd694bdb66f88902018a54cfe2b24cf434deb86d2f9f0f2d26568951b");
}

test "UserSetAbstraction: matches Python SDK" {
    const s = try Signer.fromHex(test_key);
    const addr5b = hexToBytes(20, "0000000000000000000000000000000000000005");
    const sig = try eip712.signUserSetAbstraction(s, is_mainnet, addr5b, "test-abstraction", time);
    try expectSig(sig, "2c5314f0aa305f0671fdd5013e230d5355083be38210a73e46ac9736eebbb5fd34d7846c145cfc4207e8dbb5c0559ceae84806cfb1973d2cae7c05d834c05c0f1b");
}

// ── L1 action msgpack cross-validation ────────────────────────
// Vectors from Python SDK tests/signing_test.py

const types = hlz.hypercore.types;
const signing = hlz.hypercore.signing;
const msgpack = hlz.encoding.msgpack;

test "msgpack: subAccountTransfer bytes match Python SDK" {
    var buf: [256]u8 = undefined;
    var p = msgpack.Packer.init(&buf);
    try types.packActionSubAccountTransfer(&p, .{
        .sub_account_user = "0x1d9470d4b963f552e6f671a81619d395877bf409",
        .is_deposit = true,
        .usd = 10,
    });
    const expected = hexToBytes(100, "84a474797065b27375624163636f756e745472616e73666572ae7375624163636f756e7455736572d92a307831643934373064346239363366353532653666363731613831363139643339353837376266343039a969734465706f736974c3a37573640a");
    try std.testing.expectEqualSlices(u8, &expected, p.written());
}

test "msgpack: createSubAccount bytes match Python SDK" {
    var buf: [128]u8 = undefined;
    var p = msgpack.Packer.init(&buf);
    try types.packActionCreateSubAccount(&p, .{ .name = "example" });
    const expected = hexToBytes(36, "82a474797065b06372656174655375624163636f756e74a46e616d65a76578616d706c65");
    try std.testing.expectEqualSlices(u8, &expected, p.written());
}

test "msgpack: vaultTransfer bytes match Python SDK" {
    var buf: [256]u8 = undefined;
    var p = msgpack.Packer.init(&buf);
    try types.packActionVaultTransfer(&p, .{
        .vault_address = "0x1234567890abcdef1234567890abcdef12345678",
        .is_deposit = true,
        .usd = 100,
    });
    const expected = hexToBytes(93, "84a474797065ad7661756c745472616e73666572ac7661756c7441646472657373d92a307831323334353637383930616263646566313233343536373839306162636465663132333435363738a969734465706f736974c3a375736464");
    try std.testing.expectEqualSlices(u8, &expected, p.written());
}

test "L1 sign: subAccountTransfer signature matches Python SDK" {
    const s = try Signer.fromHex("0123456789012345678901234567890123456789012345678901234567890123");
    const sat = types.SubAccountTransfer{
        .sub_account_user = "0x1d9470d4b963f552e6f671a81619d395877bf409",
        .is_deposit = true,
        .usd = 10,
    };
    const sig = try signing.signSubAccountTransfer(s, sat, 0, .mainnet, null, null);
    try expectSig(sig, "43592d7c6c7d816ece2e206f174be61249d651944932b13343f4d13f306ae60271a926cb5c9a7c01c3359ec4c4c34c16ff8107d610994d4de0e6430e5cc0f4c91c");
}

test "L1 sign: createSubAccount signature matches Python SDK" {
    const s = try Signer.fromHex("0123456789012345678901234567890123456789012345678901234567890123");
    const csa = types.CreateSubAccount{ .name = "example" };
    const sig = try signing.signCreateSubAccount(s, csa, 0, .mainnet, null, null);
    try expectSig(sig, "51096fe3239421d16b671e192f574ae24ae14329099b6db28e479b86cdd6caa70b71f7d293af92d3772572afb8b102d167a7cef7473388286bc01f52a5c5b4231b");
}
